server:
  port: 8888

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/ZenShop?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: zxw030406
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  data:
    redis:
      host: localhost
      port: 6379
      password: zxw030406

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: cn.zenshop.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
          logic-delete-field: isDelete
          logic-delete-value: 0
          logic-not-delete-value: 1
obs:
  access-key: HPUAGFQIKY0VTZKQ8DYH
  secret-key: SWgRyLKnAfT7ph8714oaox1E5ozYImieJ2On9VBc
  bucket-name: zxw-web-framework
  endpoint: obs.cn-north-4.myhuaweicloud.com
knife4j:
  enable: false
  setting:
    language: zh_cn